development:
  adapter: sqlite3
  encoding: unicode
  database: writers_tc_development
  pool: 5

test:
  adapter: sqlite3
  encoding: unicode
  database: writers_tc_test
  pool: 5

production:
  adapter: postgresql
  database: writers_tc_production
  pool: 5
  timeout: 5000